import { PublicLegalPage } from "@/components/public-legal-page";

export const metadata = { title: "Privacy" };

export default function PrivacyPage() {
  return <PublicLegalPage label="Legal / Privacy" title="Privacy notice" intro="This notice explains the information Proofwork processes to provide account access, independent outcome verification, and a durable evidence history." sections={[
    { title: "Information we process", body: <><p>We process account identity, workspace settings, authorized requests, agent reports, source observations, approvals, and activity events submitted to or generated by the service.</p><p>Google sign-in requests only OpenID Connect identity, email, and basic profile information.</p></> },
    { title: "Why we process it", body: <p>Information is used to authenticate people, keep workspaces separate, verify reported outcomes, apply explicitly approved recovery actions, prevent abuse, and maintain the audit record.</p> },
    { title: "Sharing and subprocessors", body: <p>Hosted deployments use infrastructure providers for application hosting, authentication, databases, and background processing. Information is not sold or used to train advertising profiles.</p> },
    { title: "Retention and deletion", body: <p>Private workspace records remain until the workspace owner requests deletion or the deployment defines a shorter retention period. Isolated demo data expires automatically and is purged on its retention schedule.</p> },
    { title: "Your choices", body: <p>You may use email and password instead of Google, export the visible activity history, ask the workspace owner to correct profile information, or request workspace deletion.</p> },
    { title: "Questions", body: <p>Send privacy or deletion requests through the support channel identified by your Proofwork deployment owner. The owner is responsible for publishing current contact and jurisdiction details before production launch.</p> },
  ]} />;
}
